#!/usr/bin/env bash
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5
# Otherwise, displays the number, in a list format


NUMBER=1
while [ $NUMBER -lt 101 ]
do
	if [ $((NUMBER%15)) = 0 ]
	then
		echo "FizzBuzz"
	elif [ $((NUMBER%3)) = 0 ]
	then
		echo "Fizz"
	elif [ $((NUMBER%5)) = 0 ]
	then
		echo "Buzz"
	else
		echo "$NUMBER"
	fi
	((NUMBER+=1))
done
