#!/usr/bin/env bash
# displays 4 and then "bad luck from China" for the 4th loop iteration
# displays 9 and then "bad luck from Japan" for the 9th loop iteration
# displays 17 and then "bad luck from Italy" for the 17th loop iteration

COUNTER=1
while [ $COUNTER -lt 21 ]
do 
	case $COUNTER in

		4)
			echo $COUNTER
			echo "bad luck from China"
			;;

		9)
			echo $COUNTER
			echo "bad luck from Japan"
			;;

		17)
			echo $COUNTER
			echo "bad luck from Italy"
			;;

		*)
			echo $COUNTER
			;;
	
	esac

	((COUNTER+=1))
done
